### ISSUE TITLE
Getting a Random crash 

### ISSUE THREAD

**Issue by praneethalla93** [vovkasm/react-native-web-image#6] opened 2017-04-14 17:45 UTC
> ---------

 beginning of crash
03-13 13:35:00.064 11909 11909 E AndroidRuntime: FATAL EXCEPTION: main
03-13 13:35:00.064 11909 11909 E AndroidRuntime: Process:com.poc.testsample, PID: 11909
03-13 13:35:00.064 11909 11909 E AndroidRuntime: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'source' of a view managed by: WebImageView
03-13 13:35:00.064 11909 11909 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:89)
03-13 13:35:00.064 11909 11909 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:123)
03-13 13:35:00.064 11909 11909 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:42)
03-13 13:35:00.064 11909 11909 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:38)
03-13 13:35:00.064 11909 11909 E AndroidRuntime: 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:227)
03-13 13:35:00.064 11909 11909 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:148)
03-13 13:35:00.064 11909 11909 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:776)
03-13 13:35:00.064 11909 11909 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:829)
03-13 13:35:00.064 11909 11909 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue.access$1500(UIViewOperationQueue.java:44)
03-13 13:35:00.064 11909 11909 E AndroidRuntime: 	at com.facebook.react.uimanager.UIViewOperationQueue$3.run(UIViewOperationQueue.java:807)
03-13 13:35:00.064 11909 11909 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
03-13 13:35:00.064 11909 11909 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-13 13:35:00.064 11909 11909 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
03-13 13:35:00.064 11909 11909 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6688)
03-13 13:35:00.064 11909 11909 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-13 13:35:00.064 11909 11909 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
03-13 13:35:00.064 11909 11909 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
03-13 13:35:00.064 11909 11909 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
03-13 13:35:00.064 11909 11909 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-13 13:35:00.064 11909 11909 E AndroidRuntime: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:77)
03-13 13:35:00.064 11909 11909 E AndroidRuntime: 	... 16 more
03-13 13:35:00.064 11909 11909 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
03-13 13:35:00.064 11909 11909 E AndroidRuntime: 	at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:134)
03-13 13:35:00.064 11909 11909 E AndroidRuntime: 	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:125)
03-13 13:35:00.064 11909 11909 E AndroidRuntime: 	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:89)
03-13 13:35:00.064 11909 11909 E AndroidRuntime: 	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:91)
03-13 13:35:00.064 11909 11909 E AndroidRuntime: 	at com.bumptech.glide.Glide.with(Glide.java:629)
03-13 13:35:00.064 11909 11909 E AndroidRuntime: 	at org.vovkasm.WebImage.WebImageViewManager.setSrc(WebImageViewManager.java:75)
03-13 13:35:00.064 11909 11909 E AndroidRuntime: 	... 18 more
03-13 13:35:00.066 11909 11932 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
03-13 13:35:00.066 11909 11932 I System.out: (HTTPLog)-Static: isSBSettingEnabled false
03-13 13:35:00.067   986  1999 D EnterpriseController: netId is 

> 0

I am seeing a random crash sometimes. I have googled for it and found some resources which I pasted below. Can you please take a look

https://github.com/bumptech/glide/issues/138
https://github.com/bumptech/glide/issues/803

Thanks

**Comment by vovkasm** [comment] 2017-04-15 05:13
Thank you for research!

Yes, I will look at the issue today.

**Comment by vovkasm** [comment] 2017-04-15 11:59
Can you check branch [android-crashes](https://github.com/vovkasm/react-native-web-image/tree/android-crashes)? This and #4 should be fixed.

If you can't reproduce errors locally, then I can simply release new version to npm.

**Comment by praneethalla93** [comment] 2017-04-17 23:58
I tried with this branch but not able to reproduce it. Hopefully it will solve the problem. Thank you for fixing this issue. Please release a new version whenever you get some time.

**Closed** 2017-04-18 13:17 UTC

**Comment by gvillenave** [comment] 2017-10-02 21:30
@vovkasm I have been seeing this crash on 0.0.4. Is the fix merged into 0.0.5? Thanks!

**Comment by vovkasm** [comment] 2017-10-03 05:28
@gvillenave Yes, this was merged into 0.0.5
